# Generated by Django 4.0.4 on 2022-10-20 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsofgoods',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goods',
            name='categoryGoods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopPlatform.categoryofgoods', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imageGoods',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/', verbose_name='Каталог фото'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='manufacturerOfGoods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopPlatform.manufacturer', verbose_name='Производитель товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sellerGoods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец товара'),
        ),
    ]
