# Generated by Django 4.0.4 on 2022-10-25 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopPlatform', '0002_commentsofgoods_user_alter_goods_categorygoods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='imageGoods',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Каталог фото'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakazGuman', models.CharField(max_length=100,)),
                ('goodsZacaz', models.CharField(max_length=100,verbose_name='Название товара')),
                ('countGoods', models.IntegerField(verbose_name='Кол-во товара')),
                ('priceGoods', models.IntegerField(verbose_name='Цена за ед')),
                ('sellerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopPlatform.goods', verbose_name='Продавец товара')),
            ],
        ),
    ]
